name: MLflow CI/CD Pipeline - Model Retraining & Dockerize

on:
  push:
    branches:
      - main  
    paths:
      - 'MLProject/**' # Trigger jika ada perubahan pada kode/data model
  workflow_dispatch: 

jobs:
  mlflow_retrain_and_dockerize:
    runs-on: ubuntu-latest
    
    # 1. Menetapkan kredensial DagsHub dan Docker Hub dari Secrets
    env:
      # Kredensial MLflow/DagsHub untuk Tracking
      MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_MLFLOW_URI }} 
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }} 
      
      # Kredensial Docker Hub untuk Push Image
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Dependencies
        # Instal semua dependensi yang diperlukan untuk menjalankan modelling.py
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn dagshub joblib
          
      # 2. Run MLflow Project (Retraining) - Mengatasi Error 'activate'
      - name: Run MLflow Project (Model Retraining)
        run: |
          cd MLProject
          mlflow run .
          
      # 3. Login ke Docker Hub (Kriteria 3: Advance)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Ambil Run ID Terbaik dari DagsHub
      - name: Get Latest Successful Run ID
        id: get_run_id
        run: |
          # Ambil Run ID dengan R2 Score tertinggi
          RUN_ID=$(mlflow search runs --experiment-names "Default" --order-by "metrics.r2_score DESC" --max-results 1 --output-columns "run_id" | awk 'NR>1 {print $1}')
          
          if [ -z "$RUN_ID" ]; then
            echo "::error::Tidak ada run yang ditemukan di DagsHub. Pastikan Kriteria 2 berhasil."
            exit 1
          fi
          echo "LATEST_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
      # 5. Build dan Push Docker Image (Kriteria 3: Advance)
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/salaries-model-ci:latest
          
          # MODEL_URI menunjuk ke lokasi file model yang di-log di Kriteria 2
          MODEL_URI=runs:/${{ env.LATEST_RUN_ID }}/ridge_model/best_ridge_model.pkl 

          echo "Membangun Docker Image dari $MODEL_URI"
          
          mlflow build-docker --model-uri $MODEL_URI --name $IMAGE_NAME
          
          docker push $IMAGE_NAME
