name: MLflow CI Workflow 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/netflix-ci 

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.10'
          auto-activate-base: false 

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project (Train Model - Hardcoded)
        run: |
          export MLFLOW_TRACKING_URI="https://dagshub.com/nunohadianto/my-first-repo.mlflow"
          export MLFLOW_TRACKING_USERNAME="nunohadianto"
          export MLFLOW_TRACKING_PASSWORD="afe2c28404bd7ea3ee6c8c7db28c922656b49bef" 
          
          mlflow run MLProject/
        
      - name: Read Run ID
        id: read_run_id
        run: echo "RUN_ID=$(cat MLProject/run_id.txt)" >> $GITHUB_OUTPUT
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_URI }}
        run: |
          RUN_ID=${{ steps.read_run_id.outputs.RUN_ID }}
          echo "Membangun image dari Run ID: $RUN_ID"
          
          # Sekarang mlflow build-docker tahu harus mencari run di DagsHub
          mlflow models build-docker \
            -m "runs:/${RUN_ID}/model" \
            -n "${{ env.IMAGE_NAME }}:latest"

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:latest
         
      - name: Upload Run ID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-run-id
          path: MLProject/run_id.txt
