name: MLflow CI Workflow 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    # Nama Image Docker Hub Anda (Masih pakai Secret)
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/netflix-ci 

    steps:
      # 1. Checkout kode
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Setup Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.10'
          auto-activate-base: false 

      # 3. Install MLflow
      - name: Install MLflow
        run: pip install mlflow

      # 4. Menjalankan MLflow Project (Training)
      # MENGATUR ENV VARS LANGSUNG DI SINI (TIDAK AMAN!)
      - name: Run MLflow Project (Train Model - Hardcoded)
        run: |
          export MLFLOW_TRACKING_URI="https://dagshub.com/nunohadianto/my-first-repo.mlflow"
          export MLFLOW_TRACKING_USERNAME="nunohadianto"
          export MLFLOW_TRACKING_PASSWORD="afe2c28404bd7ea3ee6c8c7db28c922656b49bef" 
          
          mlflow run .
        
      # 5. Baca Run ID 
      - name: Read Run ID
        id: read_run_id
        run: echo "RUN_ID=$(cat run_id.txt)" >> $GITHUB_OUTPUT
      
      # 6. Login ke Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Build Docker Image 
      - name: Build Docker Image with MLflow
        run: |
          RUN_ID=${{ steps.read_run_id.outputs.RUN_ID }}
          echo "Membangun image dari Run ID: $RUN_ID"
          mlflow models build-docker \
            -m "runs:/${RUN_ID}/model" \
            -n "${{ env.IMAGE_NAME }}:latest"

      # 8. Push Docker Image 
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:latest
        
      # 9. Upload Run ID Artifact
      - name: Upload Run ID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-run-id
          path: run_id.txt
