name: MLflow CI Workflow (Retraining)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # 1. Checkout kode repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Setup Miniconda 
      # Menggunakan action standar untuk setup conda.
      # Action akan meng-install conda DAN meng-inisialisasi shell
      # untuk semua langkah berikutnya.
      - name: Set up Miniconda
        uses: conda-actions/setup-miniconda@v3
        with:
          python-version: '3.10'
          # 'auto-activate-base: false' lebih aman harusnya brr, 
          # karena MLflow akan mengaktifkan env-nya sendiri
          auto-activate-base: false 

      # 3. Install MLflow di environment base
      # perlu MLflow di 'base' untuk bisa menjalankan 'mlflow run'
      - name: Install MLflow
        run: pip install mlflow

      # 4. Menjalankan MLflow Project
      # harusnya 'mlflow run' bisa menemukan 'conda'
      # dan 'conda' bisa menemukan 'activate'
      - name: Run MLflow Project
        run: mlflow run .

      # 5. Upload Artefak 
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifact
          path: model/ # Path ke folder yang berisi model.pkl
